Implemented authentication with key for applications
ampcc/coding-challenge pull request #140
Opened 2023-04-24 20:46 UTC by Marcodaum

2023-04-24 21:16 UTC, lorenzschreyer approved these changes

2023-04-25 08:06 UTC, 23ari requested changes

2023-04-25 08:06 UTC, 23ari commented on backend/codingchallenge/api/views/applications.py
Use Django settings conf instead of loading dotenv again.

2023-04-25 14:45 UTC, 23ari approved these changes

2023-04-25 14:45 UTC, merged