Feature/postgre database tests
ampcc/coding-challenge pull request #330
Opened 2023-05-26 19:39 UTC by HeiligeMeier

2023-05-27 09:31 UTC, ThmsRchhrzr approved these changes
wenn alle Tests mit der Postgre funktionieren, dann OK

2023-05-28 15:20 UTC, Marcodaum requested changes

2023-05-28 15:20 UTC, Marcodaum commented on backend/codingchallenge/api/tests/views/application/test_editApplication.py
> +        # print(Application.objects.count())
remove print statements completely

2023-05-28 15:20 UTC, Marcodaum commented on backend/codingchallenge/codingchallenge/settings.py
> +# if 'test' in sys.argv:
remove commented code

2023-05-30 17:41 UTC, lorenzschreyer approved these changes

2023-06-02 10:31 UTC, FabianBretz requested changes
Is this related to #252 ?
If so, please link this issue to the PR, so that it gets automatically closed.

2023-06-02 13:35 UTC, FabianBretz approved these changes

2023-06-04 16:48 UTC, Marcodaum approved these changes

2023-06-04 16:48 UTC, merged