added support for apple silicon architecture
ampcc/coding-challenge pull request #352
Opened 2023-05-31 15:53 UTC by Marcodaum

2023-05-31 20:29 UTC, 23ari approved these changes

2023-05-31 20:39 UTC, lorenzschreyer approved these changes

2023-06-01 04:42 UTC, FabianBretz requested changes
What does this line of code do to the container exactly?

2023-06-01 08:12 UTC, Marcodaum commented
> 

The line of code installs the libffi library. Somehow the python version of libffi doesnt work and throws errors. When installing it manually before the requirements get installed it works. See: https://stackoverflow.com/questions/45028650/docker-image-with-python-alpine-failure-due-missing-compiler-error

2023-06-01 09:05 UTC, FabianBretz approved these changes

2023-06-01 09:06 UTC, merged