fixed linter result bug
ampcc/coding-challenge pull request #392
Opened 2023-06-09 12:03 UTC by lorenzschreyer

2023-06-09 12:03 UTC, KRIYO144 approved these changes

2023-06-09 12:19 UTC, vis9494 approved these changes

2023-06-09 12:38 UTC, Marcodaum requested changes
\\n was also set above. For our machine the \n had to be escaped -> \\n....

2023-06-09 15:48 UTC, lorenzschreyer commented
@Marcodaum on my machine if "\\n" is used instead of "\n" the get Result method returns a empty list. Also this is probably the fix for the Problem of @vis9494, because she also gets an empty list.

2023-06-09 19:59 UTC, FabianBretz commented on backend/codingchallenge/api/include/procedureGithubAPI.py
> +        # print(cleanSummary)
Remove debug prints

2023-06-09 19:59 UTC, FabianBretz commented on backend/codingchallenge/api/include/procedureGithubAPI.py
> +        print(result)
Same as above

2023-06-09 20:00 UTC, FabianBretz requested changes
Forgot to remove debug prints

2023-06-10 06:15 UTC, lorenzschreyer commented on backend/codingchallenge/api/include/procedureGithubAPI.py
> +        print(result)
done

2023-06-10 06:16 UTC, lorenzschreyer commented on backend/codingchallenge/api/include/procedureGithubAPI.py
> +        # print(cleanSummary)
done

2023-06-10 20:41 UTC, Marcodaum approved these changes

2023-06-10 21:01 UTC, FabianBretz approved these changes
lgtm

2023-06-11 12:12 UTC, merged